###############################################################################
dataDir=data
###############################################################################
corpusDir=/home/airenas/hdd/projects/lm/corpus/tekstynas_admin
toolsDir=../../tools/bin
